### ISSUE TITLE
Subpixel resolution fails

### ISSUE THREAD

**Issue by fmeyenhofer** [tischi/fiji-correct-3d-drift#3]
with the subpixel resolution the shifts are calculated, but when starting to apply them, it fails at the very first iteration with the error:

```
Traceback (most recent call last):
  File "Plugins/Registration/Correct_3D_Drift_Plus--ImgLib2.py", line 603, in <module>
  File "Plugins/Registration/Correct_3D_Drift_Plus--ImgLib2.py", line 579, in run
  File "Plugins/Registration/Correct_3D_Drift_Plus--ImgLib2.py", line 444, in register_hyperstack_subpixel
  File "Plugins/Registration/Correct_3D_Drift_Plus--ImgLib2.py", line 63, in translate_single_stack_using_imglib2
    at net.imglib2.position.transform.Floor.move(Floor.java:152)
    at net.imglib2.realtransform.AffineRandomAccessible$AffineRandomAccess.bck(AffineRandomAccessible.java:105)
    at net.imglib2.view.RandomAccessibleIntervalCursor.reset(RandomAccessibleIntervalCursor.java:137)
    at net.imglib2.view.RandomAccessibleIntervalCursor.<init>(RandomAccessibleIntervalCursor.java:79)
    at net.imglib2.view.IterableRandomAccessibleInterval.cursor(IterableRandomAccessibleInterval.java:103)
    at net.imglib2.view.IterableRandomAccessibleInterval.iterator(IterableRandomAccessibleInterval.java:97)
    at net.imglib2.view.IntervalView.iterator(IntervalView.java:162)
    at net.imglib2.view.Views.iterable(Views.java:743)
    at net.imglib2.display.projector.IterableIntervalProjector2D.map(IterableIntervalProjector2D.java:119)
    at net.imglib2.img.display.imagej.ImageJVirtualStack.getProcessor(ImageJVirtualStack.java:174)
    at ij.ImagePlus.setStack(ImagePlus.java:661)
    at ij.ImagePlus.<init>(ImagePlus.java:149)
    at net.imglib2.img.display.imagej.ImageJFunctions.makeImagePlus(ImageJFunctions.java:285)
    at net.imglib2.img.display.imagej.ImageJFunctions.wrapUnsignedShort(ImageJFunctions.java:488)
    at net.imglib2.img.display.imagej.ImageJFunctions.wrapUnsignedShort(ImageJFunctions.java:475)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)

java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 2
```

assuming 4e3d9335a3afe8689c0113b83eb5a60442ec931d was the version you posed in the [forum](http://forum.imagej.net/t/correct-3d-drift-erratic-behaviour-with-two-channel-stacks/2987/12)

**Comment by tischi** [comment]
Hi, 
Very weird error. 
Could you send me the data that you used? 
Or did you use **161010_larisa.tif**?

**Comment by tischi** [comment]
For me it works for both 2D and 3D images.
Just to be sure I uploaded the latest version again: https://github.com/tischi/fiji-correct-3d-drift/commit/7a38414fed650ceb3645dce0c71812251497e001

**Comment by fmeyenhofer** [comment]
Ok, I checked out your latest commit and run it on the [dataset](https://drive.switch.ch/index.php/s/DQnpJy20vIGOFND) I also posed in the forum. The channel mixup still happens when checking the sub-pixel resolution:
<img width="308" alt="screen shot 2016-10-14 at 17 59 08" src="https://cloud.githubusercontent.com/assets/729273/19394132/11524716-9238-11e6-92f7-0ad4570c96f5.png">
<img width="308" alt="screen shot 2016-10-14 at 17 59 21" src="https://cloud.githubusercontent.com/assets/729273/19394144/16f3ee18-9238-11e6-80cb-2d20c6c2d13c.png">

I still use the ImageScience update site. Could this have an impact?

**Comment by fmeyenhofer** [comment]
Tried without the ImageScience update site. Interestingly all the transformations that are applied have integer numbers (all x.0). The output still looks the same as posted previously.

**Comment by tischi** [comment]
I cannot reproduce it. For me it works. 
I did it again today at home.
It does not produce a channel mix anymore up as far as I can judge.

I attach input data, output data, the script (which is just a copy and paste from github) and a screenshot of my settings and the Fiji and java version. 

[3d-drift.zip](https://github.com/tischi/fiji-correct-3d-drift/files/531043/3d-drift.zip)

![screen shot 2016-10-15 at 10 26 58](https://cloud.githubusercontent.com/assets/2157566/19408658/158cb290-92c3-11e6-9d3e-ca5b352dfad4.png)

Does the output data look ok to you? Do you get the same result (I registered on Ch1).

How do you run the script? I drag and drop onto Fiji and run it from the script editor using the [Run] button. You see that you execute the new version, because it has a new option (not yet functional) to only compute the drifts but not apply them.

![screen shot 2016-10-15 at 10 25 36](https://cloud.githubusercontent.com/assets/2157566/19408656/13514b30-92c3-11e6-8239-c49fec2a0a8a.png)

**Comment by tischi** [comment]
Just as a side-remark: If you look at the Ch1 in your data set, the pixel intensity values are exactly the same at least for the first 5 time-points, even no changes in the noise. It looks like it is just the same data, but copy and paste into the different time-points. Can you explain me what Ch1 actually is?

**Comment by fmeyenhofer** [comment]
I checked this repository out, and put the script in Fiji.app/plugins/Scripts/Plugins/Registration. Then I ran the script via the menu.
Now I ran the script from your zip-file via the script-editor. This works indeed. Is this the same version as the head of this repository?

As for the data. Yes, Ch1 is one and the same image. In order to have a high frame rate, the nuclei are imaged only at the beginning of the time-series.

**Comment by tischi** [comment]
OK! 
Moving it to Fiji.app/plugins/Scripts/Plugins/Registration would only work when you **_restart_** Fiji!
So we conclude that the version in my repo works!
You can use my script for now. I will try to push it to the Fiji release soon.

**Comment by fmeyenhofer** [comment]
I did restart... that's what's bugging me. But it should be fine to go ahead. Thanks.

**Comment by tischi** [comment]
hmm, weird. what happens if you remove the script completely and then restart. does it still show up as a menu item? if so, maybe you should ask in the IJ forum what is going on.

**Comment by fmeyenhofer** [comment]
> On 17 Oct 2016, at 13:36, tischi notifications@github.com wrote:
> 
> hmm, weird. what happens if you remove the script completely and then restart. does it still show up as a menu item?
> no, of course not. 
> if so, maybe you should ask in the IJ forum what is going on.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

What is bugging me is that 
https://github.com/tischi/fiji-correct-3d-drift/blob/master/2016-03-04--Tischi--Correct_3D_Drift_Plus--ImgLib2.py

running this from the script editor still yield weird results. My local copy (git log)

```
commit 7a38414fed650ceb3645dce0c71812251497e001
Author: Christian "Tischi" Tischer <tischitischer@gmail.com>
Date:   Fri Oct 14 21:04:13 2016 +0530
```

However the when using the zip file you posted previously then it works.
But a diff on the file from the zip-archive and the one in the repository yields a great many lines. But you keep insisting that they are the same... this confuses me...

**Comment by tischi** [comment]
Ah, no, I am not at all insisting; probably I got mixed up :-)
I uploaded a new version to git-hub today: https://github.com/tischi/fiji-correct-3d-drift/commit/7a639ae8f751fb76b642c49c4c142d8ce40502ec
Does that work for you?

**Comment by fmeyenhofer** [comment]
misunderstanding then. 
yes, https://github.com/tischi/fiji-correct-3d-drift/blob/master/Correct_3D_Drift_Plus--ImgLib2.py works (not the other two though, but they haven't been modified)

**Comment by tischi** [comment]
ok! thank you for testing!

**Comment by fmeyenhofer** [comment]
thanks for fixing. The vector output is also a good idea.
